In [1]:
import pandas as pd
import numpy as np

In [2]:
adult = pd.read_csv('adult_test.csv',sep=';')
adult.head(10)

,Age,Workclass,fnlwgt,Education,Education_Num,Martial_Status,Occupation,Relationship,Race,Sex,Capital_Gain,Capital_Loss,Hours_per_week,Country,Target
0,25,Private,226802.0,11th,7.0,Never-married,Machine-op-inspct,Own-child,Black,Male,0.0,0.0,40.0,United-States,<=50K.
1,38,Private,89814.0,HS-grad,9.0,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K.
2,28,Local-gov,336951.0,Assoc-acdm,12.0,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40.0,United-States,>50K.
3,44,Private,160323.0,Some-college,10.0,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688.0,0.0,40.0,United-States,>50K.
4,18,NaN,103497.0,Some-college,10.0,Never-married,NaN,Own-child,White,Female,0.0,0.0,30.0,United-States,<=50K.
5,34,Private,198693.0,10th,6.0,Never-married,Other-service,Not-in-family,White,Male,0.0,0.0,30.0,United-States,<=50K.
6,29,NaN,227026.0,HS-grad,9.0,Never-married,NaN,Unmarried,Black,Male,0.0,0.0,40.0,United-States,<=50K.
7,63,Self-emp-not-inc,104626.0,Prof-school,15.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,3103.0,0.0,32.0,United-States,>50K.
8,24,Private,369667.0,Some-college,10.0,Never-married,Other-service,Unmarried,White,Female,0.0,0.0,40.0,United-States,<=50K.
9,55,Private,104996.0,7th-8th,4.0,Married-civ-spouse,Craft-repair,Husband,White,Male,0.0,0.0,10.0,United-States,<=50K.

In [3]:
adult.describe()

,Age,fnlwgt,Education_Num,Capital_Gain,Capital_Loss,Hours_per_week
count,16281.000000,1.628100e+04,16281.000000,16281.000000,16281.000000,16281.000000
mean,38.767459,1.894357e+05,10.072907,1081.905104,87.899269,40.392236
std,13.849187,1.057149e+05,2.567545,7583.935968,403.105286,12.479332
min,17.000000,1.349200e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.167360e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.778310e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.383840e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,3770.000000,99.000000

In [4]:
np.sum(adult.isnull())

Age                 0
Workclass         963
fnlwgt              0
Education           0
Education_Num       0
Martial_Status      0
Occupation        966
Relationship        0
Race                0
Sex                 0
Capital_Gain        0
Capital_Loss        0
Hours_per_week      0
Country           274
Target              0
dtype: int64

In [5]:
from scipy.stats import mode

adult['Workclass'] = adult['Workclass'].fillna(adult['Workclass']).dropna().mode()[0]
adult['Occupation'] = adult['Occupation'].fillna(adult['Occupation']).dropna().mode()[0]
adult['Country'] = adult['Country'].fillna(adult['Country']).dropna().mode()[0]

In [6]:
np.sum(adult.isnull())

Age               0
Workclass         0
fnlwgt            0
Education         0
Education_Num     0
Martial_Status    0
Occupation        0
Relationship      0
Race              0
Sex               0
Capital_Gain      0
Capital_Loss      0
Hours_per_week    0
Country           0
Target            0
dtype: int64

In [7]:
from scipy.stats import stats
z= np.abs(stats.zscore(adult._get_numeric_data()))
print(z)
adult=adult[(z<3).all(axis=1)]
print(adult.shape)

[[0.99412926 0.35347399 1.19686359 0.14266185 0.21806206 0.03143184]
 [0.05541716 0.94239062 0.41788553 0.14266185 0.21806206 0.7699177 ]
 [0.77750339 1.39544986 0.75058156 0.14266185 0.21806206 0.03143184]
 ...
 [0.05541716 1.75522095 1.14007059 0.14266185 0.21806206 0.7699177 ]
 [0.37783458 0.99842039 1.14007059 0.57664374 0.21806206 0.03143184]
 [0.27204303 0.0689392  1.14007059 0.14266185 0.21806206 1.57126723]]
(14918, 15)

In [8]:
adult

,Age,Workclass,fnlwgt,Education,Education_Num,Martial_Status,Occupation,Relationship,Race,Sex,Capital_Gain,Capital_Loss,Hours_per_week,Country,Target
0,25,Private,226802.0,11th,7.0,Never-married,Prof-specialty,Own-child,Black,Male,0.0,0.0,40.0,United-States,<=50K.
1,38,Private,89814.0,HS-grad,9.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K.
2,28,Private,336951.0,Assoc-acdm,12.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,40.0,United-States,>50K.
3,44,Private,160323.0,Some-college,10.0,Married-civ-spouse,Prof-specialty,Husband,Black,Male,7688.0,0.0,40.0,United-States,>50K.
4,18,Private,103497.0,Some-college,10.0,Never-married,Prof-specialty,Own-child,White,Female,0.0,0.0,30.0,United-States,<=50K.
5,34,Private,198693.0,10th,6.0,Never-married,Prof-specialty,Not-in-family,White,Male,0.0,0.0,30.0,United-States,<=50K.
6,29,Private,227026.0,HS-grad,9.0,Never-married,Prof-specialty,Unmarried,Black,Male,0.0,0.0,40.0,United-States,<=50K.
7,63,Private,104626.0,Prof-school,15.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,3103.0,0.0,32.0,United-States,>50K.
8,24,Private,369667.0,Some-college,10.0,Never-married,Prof-specialty,Unmarried,White,Female,0.0,0.0,40.0,United-States,<=50K.
9,55,Private,104996.0,7th-8th,4.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,10.0,United-States,<=50K.
10,65,Private,184454.0,HS-grad,9.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,6418.0,0.0,40.0,United-States,>50K.
11,36,Private,212465.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,40.0,United-States,<=50K.
12,26,Private,82091.0,HS-grad,9.0,Never-married,Prof-specialty,Not-in-family,White,Female,0.0,0.0,39.0,United-States,<=50K.
13,58,Private,299831.0,HS-grad,9.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,35.0,United-States,<=50K.
14,48,Private,279724.0,HS-grad,9.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,3103.0,0.0,48.0,United-States,>50K.
15,43,Private,346189.0,Masters,14.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,50.0,United-States,>50K.
16,20,Private,444554.0,Some-college,10.0,Never-married,Prof-specialty,Own-child,White,Male,0.0,0.0,25.0,United-States,<=50K.
17,43,Private,128354.0,HS-grad,9.0,Married-civ-spouse,Prof-specialty,Wife,White,Female,0.0,0.0,30.0,United-States,<=50K.
18,37,Private,60548.0,HS-grad,9.0,Widowed,Prof-specialty,Unmarried,White,Female,0.0,0.0,20.0,United-States,<=50K.
19,40,Private,85019.0,Doctorate,16.0,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0.0,0.0,45.0,United-States,>50K.
20,34,Private,107914.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,47.0,United-States,>50K.
21,34,Private,238588.0,Some-college,10.0,Never-married,Prof-specialty,Own-child,Black,Female,0.0,0.0,35.0,United-States,<=50K.
22,72,Private,132015.0,7th-8th,4.0,Divorced,Prof-specialty,Not-in-family,White,Female,0.0,0.0,6.0,United-States,<=50K.
23,25,Private,220931.0,Bachelors,13.0,Never-married,Prof-specialty,Not-in-family,White,Male,0.0,0.0,43.0,United-States,<=50K.
24,25,Private,205947.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,40.0,United-States,<=50K.
26,22,Private,236427.0,HS-grad,9.0,Never-married,Prof-specialty,Own-child,White,Male,0.0,0.0,20.0,United-States,<=50K.
27,23,Private,134446.0,HS-grad,9.0,Separated,Prof-specialty,Unmarried,Black,Male,0.0,0.0,54.0,United-States,<=50K.
28,54,Private,99516.0,HS-grad,9.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,35.0,United-States,<=50K.
29,32,Private,109282.0,Some-college,10.0,Never-married,Prof-specialty,Not-in-family,White,Male,0.0,0.0,60.0,United-States,<=50K.
30,46,Private,106444.0,Some-college,10.0,Married-civ-spouse,Prof-specialty,Husband,Black,Male,7688.0,0.0,38.0,United-States,>50K.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16248,25,Private,242136.0,HS-grad,9.0,Divorced,Prof-specialty,Not-in-family,Black,Male,0.0,0.0,40.0,United-States,<=50K.
16249,31,Private,112115.0,HS-grad,9.0,Never-married,Prof-specialty,Not-in-family,White,Male,0.0,0.0,40.0,United-States,<=50K.
16250,49,Private,77132.0,HS-grad,9.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,40.0,United-States,>50K.
16252,60,Private,117909.0,Assoc-voc,11.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,7688.0,0.0,40.0,United-States,>50K.
16254,38,Private,149347.0,Masters,14.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,50.0,United-States,>50K.
16256,23,Private,93977.0,HS-grad,9.0,Never-married,Prof-specialty,Own-child,White,Male,0.0,0.0,40.0,United-States,<=50K.
16257,73,Private,159691.0,Some-college,10.0,Divorced,Prof-specialty,Not-in-family,White,Female,0.0,0.0,40.0,United-States,<=50K.
16258,35,Private,176967.0,Some-college,10.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,40.0,United-States,<=50K.
16259,66,Private,344436.0,HS-grad,9.0,Widowed,Prof-specialty,Other-relative,White,Female,0.0,0.0,8.0,United-States,<=50K.
16260,27,Private,430340.0,Some-college,10.0,Never-married,Prof-specialty,Not-in-family,White,Female,0.0,0.0,45.0,United-States,<=50K.
16261,40,Private,202168.0,Prof-school,15.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,15024.0,0.0,55.0,United-States,>50K.
16262,51,Private,82720.0,HS-grad,9.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,40.0,United-States,<=50K.
16263,22,Private,269623.0,Some-college,10.0,Never-married,Prof-specialty,Own-child,White,Male,0.0,0.0,40.0,United-States,<=50K.
16264,64,Private,136405.0,HS-grad,9.0,Widowed,Prof-specialty,Not-in-family,White,Male,0.0,0.0,32.0,United-States,<=50K.
16265,50,Private,139347.0,Masters,14.0,Married-civ-spouse,Prof-specialty,Wife,White,Female,0.0,0.0,40.0,United-States,>50K.
16266,55,Private,224655.0,HS-grad,9.0,Separated,Prof-specialty,Not-in-family,White,Female,0.0,0.0,32.0,United-States,<=50K.
16267,38,Private,247547.0,Assoc-voc,11.0,Never-married,Prof-specialty,Unmarried,Black,Female,0.0,0.0,40.0,United-States,<=50K.
16268,58,Private,292710.0,Assoc-acdm,12.0,Divorced,Prof-specialty,Not-in-family,White,Male,0.0,0.0,36.0,United-States,<=50K.
16269,32,Private,173449.0,HS-grad,9.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,40.0,United-States,<=50K.
16270,48,Private,285570.0,HS-grad,9.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,40.0,United-States,<=50K.
16271,61,Private,89686.0,HS-grad,9.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,48.0,United-States,<=50K.
16272,31,Private,440129.0,HS-grad,9.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,40.0,United-States,<=50K.
16273,25,Private,350977.0,HS-grad,9.0,Never-married,Prof-specialty,Own-child,White,Female,0.0,0.0,40.0,United-States,<=50K.
16274,48,Private,349230.0,Masters,14.0,Divorced,Prof-specialty,Not-in-family,White,Male,0.0,0.0,40.0,United-States,<=50K.
16275,33,Private,245211.0,Bachelors,13.0,Never-married,Prof-specialty,Own-child,White,Male,0.0,0.0,40.0,United-States,<=50K.
16276,39,Private,215419.0,Bachelors,13.0,Divorced,Prof-specialty,Not-in-family,White,Female,0.0,0.0,36.0,United-States,<=50K.
16277,64,Private,321403.0,HS-grad,9.0,Widowed,Prof-specialty,Other-relative,Black,Male,0.0,0.0,40.0,United-States,<=50K.
16278,38,Private,374983.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K.
16279,44,Private,83891.0,Bachelors,13.0,Divorced,Prof-specialty,Own-child,Asian-Pac-Islander,Male,5455.0,0.0,40.0,United-States,<=50K.
16280,35,Private,182148.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,60.0,United-States,>50K.